package com.fptu.phucth115;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface DBField {
    String name() default "";
    String type() default "";
    String length() default "";
    boolean id() default false;
    boolean autoGenerated() default false;

    String STRING = "string";
    String INT = "int";
    String FLOAT = "float";
    String BOOLEAN = "boolean";
    String DOUBLE = "double";
    String DATE = "date";
    String DATETIME = "datetime";

}
