package com.fptu.phucth115;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SQLServerDBContext extends DBContext {
    public SQLServerDBContext(
            String instance,
            String port,
            String databaseName,
            String username,
            String password
    ) {
        try {
            instance = instance == null ? "" : "\\" + instance;
            port = port == null ? "" : ":" + port;
            String url = "jdbc:sqlserver://" + instance + port + ";databaseName=" + databaseName;
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(url, username, password);
        } catch (ClassNotFoundException | SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void insert(DBEntity entity) {
        try {
            Class type = entity.getClass();
            String tableName = getTableName(type);
            Map<DBField, Object> params = matchAttrAndData(entity,type);
            StringBuilder column = new StringBuilder();
            StringBuilder questionmark = new StringBuilder();
            for (Map.Entry<DBField, Object> entry : params.entrySet()) {
                DBField key = entry.getKey();
                if(key.autoGenerated())
                {
                    continue;
                }
                column.append(key.name()).append(",");
                questionmark.append("?,");
            }
            column = new StringBuilder(column.substring(0, column.length() - 1));
            questionmark = new StringBuilder(questionmark.substring(0, questionmark.length() - 1));
            String sql = "INSERT INTO "+ tableName + "("+ column + ") VALUES (" + questionmark + ")";
            PreparedStatement statement = connection.prepareCall(sql);
            int index =1;
            for (Map.Entry<DBField, Object> entry : params.entrySet()) {
                DBField key = entry.getKey();
                if(key.autoGenerated())
                {
                    continue;
                }
                Object value = entry.getValue();
                addParamValue(statement, index, value, key.type());
                index++;
            }
            statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(SQLServerDBContext.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    @Override
    public void update(DBEntity entity) {
        try {
            Class type = entity.getClass();
            String tableName = getTableName(type);

            Map<DBField, Object> params = matchAttrAndData(entity,type);
            Map<DBField, Object> updatedParams = new HashMap<>();
            Map<DBField, Object> idParams = new HashMap<>();

            StringBuilder sqlSetPart = new StringBuilder();
            StringBuilder sqlWhereClause = new StringBuilder(" 1=1 ");
            for (Map.Entry<DBField, Object> entry : params.entrySet()) {
                DBField key = entry.getKey();
                Object value = entry.getValue();
                if(!key.id())
                {
                    sqlSetPart.append(key.name()).append("= ?,");
                    updatedParams.put(key, value);
                }
                else
                {
                    sqlWhereClause.append(" AND ").append(key.name()).append("= ?,");
                    idParams.put(key, value);
                }
            }
            sqlSetPart = new StringBuilder(sqlSetPart.substring(0, sqlSetPart.length() - 1));
            sqlWhereClause = new StringBuilder(sqlWhereClause.substring(0, sqlWhereClause.length() - 1));
            String sql = "UPDATE "+ tableName + " SET  "+sqlSetPart +
                    " WHERE " + sqlWhereClause;
            PreparedStatement statement = connection.prepareStatement(sql);
            int index =1;
            for (Map.Entry<DBField, Object> entry : updatedParams.entrySet()) {
                DBField key = entry.getKey();
                Object value = entry.getValue();
                addParamValue(statement, index, value, key.type());
                index++;
            }

            for (Map.Entry<DBField, Object> entry : idParams.entrySet()) {
                DBField key = entry.getKey();
                Object value = entry.getValue();
                addParamValue(statement, index, value, key.type());
                index++;
            }
            statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(SQLServerDBContext.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void delete(DBEntity entity) {
        try {
            Class type = entity.getClass();
            String tableName = getTableName(type);
            Map<DBField, Object> params = matchAttrAndData(entity,type);
            Map<DBField, Object> idParams = new HashMap<>();
            StringBuilder sqlWhereClause = new StringBuilder(" 1=1 ");
            for (Map.Entry<DBField, Object> entry : params.entrySet()) {
                DBField key = entry.getKey();
                Object value = entry.getValue();
                if(key.id())
                {
                    sqlWhereClause.append(" AND ").append(key.name()).append("= ?,");
                    idParams.put(key, value);
                }
            }
            sqlWhereClause = new StringBuilder(sqlWhereClause.substring(0, sqlWhereClause.length() - 1));
            String sql = "DELETE "+ tableName + " WHERE " + sqlWhereClause;
            PreparedStatement statement = connection.prepareStatement(sql);
            int index =1;
            for (Map.Entry<DBField, Object> entry : idParams.entrySet()) {
                DBField key = entry.getKey();
                Object value = entry.getValue();
                addParamValue(statement, index, value, key.type());
                index++;
            }
            statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(SQLServerDBContext.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public <T extends DBEntity> ArrayList<T> getAll(Class<T> type) {
        ArrayList<T> list = new ArrayList<>();
        try {

            String tableName = getTableName(type);
            Map<DBField, Object> params = matchAttrAndData(type.newInstance()
                    ,type);
            StringBuilder columns = new StringBuilder();
            for (Map.Entry<DBField, Object> entry : params.entrySet()) {
                DBField key = entry.getKey();
                columns.append(key.name()).append(",");
            }
            columns = new StringBuilder(columns.substring(0, columns.length() - 1));
            String sql = "SELECT "+ columns + " FROM " + tableName ;
            PreparedStatement statement = connection.prepareStatement(sql);
            ResultSet rs = statement.executeQuery();
            while(rs.next()){
                T entity = type.newInstance();
                doORM(rs, entity);
                list.add(entity);
            }
        } catch (SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(SQLServerDBContext.class.getName()).log(Level.SEVERE, null, ex);
        }
        return list;
    }

    @Override
    public void getOne(DBEntity entity) {
        try {
            Class type = entity.getClass();
            String tableName = getTableName(type);
            Map<DBField, Object> params = matchAttrAndData(entity,type);
            Map<DBField, Object> keyParams = new HashMap<>();
            StringBuilder columns = new StringBuilder();
            StringBuilder whereClause = new StringBuilder(" 1=1 ");
            for (Map.Entry<DBField, Object> entry : params.entrySet()) {
                DBField key = entry.getKey();
                Object value = entry.getValue();
                if(key.id())
                    keyParams.put(key, value);
                columns.append(key.name()).append(",");
            }
            columns = new StringBuilder(columns.substring(0, columns.length() - 1));

            for (Map.Entry<DBField, Object> entry : keyParams.entrySet()) {
                DBField key = entry.getKey();
                whereClause.append(" AND ").append(key.name()).append(" = ? ");
            }

            String sql = "SELECT "+ columns + " FROM " + tableName + " WHERE " + whereClause ;
            PreparedStatement statement = connection.prepareStatement(sql);
            int index = 1;
            for (Map.Entry<DBField, Object> entry : keyParams.entrySet()) {
                DBField key = entry.getKey();
                Object value = entry.getValue();
                addParamValue(statement, index, value, key.type());
                index++;
            }
            ResultSet rs = statement.executeQuery();
            if(rs.next())
                doORM(rs, entity);
        } catch (SQLException ex) {
            Logger.getLogger(SQLServerDBContext.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
